# Generated by Django 3.1.2 on 2022-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='filiere',
            field=models.CharField(choices=[('INFO', 'INFO'), ('MATHS', 'MATHS'), ('PHY', 'PHY'), ('CHM', 'CHM'), ('BIOS', 'BIOS'), ('GEOS', 'GEOS')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
