# Generated by Django 3.1.2 on 2022-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='niveau',
            field=models.CharField(choices=[('1', 'L1'), ('2', 'L2'), ('3', 'L3'), ('4', 'M1'), ('5', 'M2')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='filiere',
            field=models.CharField(choices=[('1', 'INFO'), ('MATHS', 'MATHS'), ('3', 'PHY'), ('4', 'CHM'), ('5', 'BIOS'), ('6', 'GEOS')], max_length=12),
        ),
    ]
