# Generated by Django 3.1.2 on 2022-03-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('ue', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('mat', models.CharField(max_length=7)),
                ('phone', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('respo', models.CharField(max_length=255)),
                ('objet', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
